/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package smartEtl.frames;

import java.sql.Connection;
import java.util.ArrayList;

import smartEtl.core.utils;

/**
 *
 * @author furqan
 */
public class DataJtable extends javax.swing.JInternalFrame {

    /**
     * Creates new form sourceDataJtable
     */
    public DataJtable() {
    	super("Tables", true,true, true, true);
    }

    public void populateData(){
    	ArrayList[][]  data = utils.listTable(this.conn , this.table  );
    	initComponents(data);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents(ArrayList[][]  source) {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        String [] header = null;
        Object [][] data = null;
        header = new String[source[0][0].size()];
        data  = new Object[source[0][1].size()][source[0][0].size()];
        for(int i = 0 ; i < source[0][0].size() ; i++){
        	header[i] = source[0][0].get(i).toString();
        }
        for(int i = 0 ; i < source[0][1].size() ; i++){
        	ArrayList<Object> rowData = (ArrayList<Object>) source[0][1].get(i);
        	for(int j = 0 ; j < rowData.size() ; j++){
        		data[i][j] = rowData.get(j);
        	}
        }
        
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
        	data,
            header
        ));
        
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setTable(String table) {
		this.table = table;
	}

	public void setConn(Connection conn) {
		this.conn = conn;
	}
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private Connection conn;
    private String table;
    
    // End of variables declaration//GEN-END:variables
}
