/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package smartEtl.frames;

import java.awt.Color;

import javax.swing.JDesktopPane;

import smartEtl.config.Configuration;
import smartEtl.config.PropertiesName;

/**
 *
 * @author furqan
 */
public class DesktopPane extends javax.swing.JFrame {

    private JDesktopPane desktopPane;

    /**
     * Creates new form DesktopPane
     */
    public DesktopPane() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainMenue = new javax.swing.JMenuBar();
        fileMenue = new javax.swing.JMenu();
        srcConnectionMenue = new javax.swing.JMenuItem();
        destConnectionMenue = new javax.swing.JMenuItem();
        extractMenue = new javax.swing.JMenuItem();
        LoadDataMenue = new javax.swing.JMenuItem();
        exitMenue = new javax.swing.JMenuItem();
        aboutMenue = new javax.swing.JMenu();
        aboutetl = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileMenue.setText("File");

        srcConnectionMenue.setText("Source Connection");
        srcConnectionMenue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srcConnectionMenueActionPerformed(evt);
            }
        });
        fileMenue.add(srcConnectionMenue);

        destConnectionMenue.setText("Destination Connection");
        destConnectionMenue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destConnectionMenueActionPerformed(evt);
            }
        });
        fileMenue.add(destConnectionMenue);

        extractMenue.setText("Extract Data");
        extractMenue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                extractMenueActionPerformed(evt);
            }
        });
        fileMenue.add(extractMenue);

        LoadDataMenue.setText("Load Data");
        LoadDataMenue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoadDataMenueActionPerformed(evt);
            }
        });
        fileMenue.add(LoadDataMenue);

        exitMenue.setText("Exit");
        exitMenue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenueActionPerformed(evt);
            }
        });
        fileMenue.add(exitMenue);

        mainMenue.add(fileMenue);

        aboutMenue.setText("About");
        aboutMenue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenueActionPerformed(evt);
            }
        });

        aboutetl.setText("About-ETL");
        aboutetl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutetlActionPerformed(evt);
            }
        });
        aboutMenue.add(aboutetl);

        mainMenue.add(aboutMenue);

        setJMenuBar(mainMenue);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 285, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenueActionPerformed
    	Configuration.saveConfig();
    	System.exit(0);
    }//GEN-LAST:event_exitMenueActionPerformed

    private void destConnectionMenueActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        destConnection dest = new destConnection();
        dest.setLocation(100, 100);
        dest.setVisible(true);
        desktopPane.add(dest);
    } 
    
    private void aboutMenueActionPerformed(java.awt.event.ActionEvent evt) {                                                    
       
    }  

    private void srcConnectionMenueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destConnectionMenueActionPerformed
        srcConnection srcCon = new srcConnection();
        srcCon.setLocation(100, 100);
        srcCon.setVisible(true);
        desktopPane.add(srcCon);
    }//GEN-LAST:event_destConnectionMenueActionPerformed

    private void aboutetlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutetlActionPerformed
        About about = new About();
        about.setLocation(100, 100);
        about.setVisible(true);
        desktopPane.add(about);
    }//GEN-LAST:event_aboutetlActionPerformed

    private void extractMenueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_extractMenueActionPerformed
    	
    	TablesList tables = new TablesList();
    	tables.setLocation(100, 100);
    	tables.setVisible(true);
        desktopPane.add(tables);
    }//GEN-LAST:event_extractMenueActionPerformed

    private void LoadDataMenueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoadDataMenueActionPerformed
    	LoadDataDestination tables = new LoadDataDestination();
    	tables.populateData();
    	tables.setLocation(100, 100);
    	tables.setVisible(true);
        desktopPane.add(tables);
    }//GEN-LAST:event_LoadDataMenueActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem LoadDataMenue;
    private javax.swing.JMenu aboutMenue;
    private javax.swing.JMenuItem aboutetl;
    private javax.swing.JMenuItem destConnectionMenue;
    private javax.swing.JMenuItem exitMenue;
    private javax.swing.JMenuItem extractMenue;
    private javax.swing.JMenu fileMenue;
    private javax.swing.JMenuBar mainMenue;
    private javax.swing.JMenuItem srcConnectionMenue;
    // End of variables declaration//GEN-END:variables
}
