/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package smartEtl.frames;

import javax.swing.JOptionPane;

import smartEtl.config.Configuration;
import smartEtl.config.PropertiesName;
import smartEtl.core.utils;

/**
 *
 * @author furqan
 */
public class destConnection extends javax.swing.JInternalFrame {

    /**
     * Creates new form destConnection
     */
    public destConnection() {
        super("Destination Connection", true,true, true, true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        destDB = new javax.swing.JComboBox<>();
        destDBlable = new javax.swing.JLabel();
        destDBUrl = new javax.swing.JTextField();
        destDBUrlLable = new javax.swing.JLabel();
        destDBPort = new javax.swing.JTextField();
        destDBPortLable = new javax.swing.JLabel();
        destDBUserName = new javax.swing.JTextField();
        destDBUserNameLable = new javax.swing.JLabel();
        destDBPassword = new javax.swing.JTextField();
        destDBPasswordLable = new javax.swing.JLabel();
        destDBSaveButton = new javax.swing.JButton();
        destDBTestButton = new javax.swing.JButton();
        destDataBase = new javax.swing.JTextField();
        destDataBaseLable = new javax.swing.JLabel();

        destDB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MySQl Server", "SQL Server", "Postgre Server", "Oracle" }));

        destDBlable.setText("Select DB");

        destDBUrl.setBackground(new java.awt.Color(254, 254, 254));

        destDBUrlLable.setText("DB URL");

        destDBPort.setBackground(new java.awt.Color(254, 254, 254));

        destDBPortLable.setText("Port");

        destDBUserName.setBackground(new java.awt.Color(254, 254, 254));

        destDBUserNameLable.setText("User Name");

        destDBPassword.setBackground(new java.awt.Color(254, 254, 254));
        destDBPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destDBPasswordActionPerformed(evt);
            }
        });

        destDBPasswordLable.setText("Password");

        destDBSaveButton.setText("Save");
        destDBSaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destDBSaveButtonActionPerformed(evt);
            }
        });

        destDBTestButton.setText("Test");
        destDBTestButton.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                destDBTestButtonInputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        destDBTestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destDBTestButtonActionPerformed(evt);
            }
        });

        destDataBaseLable.setText("DataBase");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(destDBUrlLable, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(destDBSaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(destDBTestButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(destDBUserName)
                            .addComponent(destDBUrl)
                            .addComponent(destDB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(destDataBase)
                            .addComponent(destDBPort, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(destDBPassword, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(destDBlable, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(destDBPortLable, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(destDBUserNameLable)
                                    .addComponent(destDataBaseLable)
                                    .addComponent(destDBPasswordLable, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(destDB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(destDBlable))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(destDBUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(destDBUrlLable))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(destDBPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(destDBPortLable))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(destDataBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(destDataBaseLable))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(destDBUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(destDBUserNameLable))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(destDBPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(destDBPasswordLable))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(destDBSaveButton)
                    .addComponent(destDBTestButton))
                .addGap(34, 34, 34))
        );
        loadFields();
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadFields(){
    	int index = utils.getDriverClassIndex(Configuration.getAttribute(PropertiesName.destDriver));
    	String url  = Configuration.getAttribute(PropertiesName.destUrl);
    	String port = Configuration.getAttribute(PropertiesName.destPort);
    	String database = Configuration.getAttribute(PropertiesName.destDB);
    	String user = Configuration.getAttribute(PropertiesName.destUser);
    	String pass = Configuration.getAttribute(PropertiesName.destPassword);
    	destDB.setSelectedIndex(index);
    	destDBUrl.setText(url);
    	destDBPort.setText(port);
    	destDataBase.setText(database);
    	destDBUserName.setText(user);
    	destDBPassword.setText(pass);
    }
    private void destDBTestButtonInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_destDBTestButtonInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_destDBTestButtonInputMethodTextChanged

    private void destDBTestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destDBTestButtonActionPerformed
    	int index = destDB.getSelectedIndex();
    	String url  = destDBUrl.getText();
    	String port = destDBPort.getText();
    	String database = destDataBase.getText();
    	String user = destDBUserName.getText();
    	String pass = destDBPassword.getText();
    	boolean status = this.testDB(index, url, port,database, user, pass); 
    	if( status )
        JOptionPane.showMessageDialog(this, "DB Ping Sucessfully");
        else
        JOptionPane.showMessageDialog(this, "Error in Connection");
    }//GEN-LAST:event_destDBTestButtonActionPerformed

    private boolean testDB(int index,String url,String port,String database, String user,String pass){
    	boolean status = utils.testConnection(index,url,port,database,user,pass);
    	return status;
    }
    private void destDBSaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destDBSaveButtonActionPerformed
    	int index = destDB.getSelectedIndex();
    	String driverClass = utils.getDriverClass(index);
    	String url  = destDBUrl.getText();
    	String port = destDBPort.getText();
    	String database = destDataBase.getText();
    	String user = destDBUserName.getText();
    	String pass = destDBPassword.getText();
    	boolean status = this.testDB(index, url ,port,database, user, pass);
        if( status ){
        	Configuration.addAttribute(PropertiesName.destDriver, driverClass);
        	Configuration.addAttribute(PropertiesName.destUrl, url);
        	Configuration.addAttribute(PropertiesName.destPort, port);
        	Configuration.addAttribute(PropertiesName.destUser, user);
        	Configuration.addAttribute(PropertiesName.destDB, database);
        	Configuration.addAttribute(PropertiesName.destPassword, pass);
        	Configuration.saveConfig();
            JOptionPane.showMessageDialog(this, "Data Saved");
        }
        else
            JOptionPane.showMessageDialog(this, "Error in Connection- fix Params");
    }//GEN-LAST:event_destDBSaveButtonActionPerformed

    private void destDBPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destDBPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_destDBPasswordActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> destDB;
    private javax.swing.JTextField destDBPassword;
    private javax.swing.JLabel destDBPasswordLable;
    private javax.swing.JTextField destDBPort;
    private javax.swing.JLabel destDBPortLable;
    private javax.swing.JButton destDBSaveButton;
    private javax.swing.JButton destDBTestButton;
    private javax.swing.JTextField destDBUrl;
    private javax.swing.JLabel destDBUrlLable;
    private javax.swing.JTextField destDBUserName;
    private javax.swing.JLabel destDBUserNameLable;
    private javax.swing.JLabel destDBlable;
    private javax.swing.JTextField destDataBase;
    private javax.swing.JLabel destDataBaseLable;
    // End of variables declaration//GEN-END:variables
}
