/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package smartEtl.frames;

import java.io.File;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
import javax.swing.filechooser.FileNameExtensionFilter;

import smartEtl.config.Configuration;

/**
 *
 * @author furqan
 */
public class mainWindow extends javax.swing.JFrame {

    /**
     * Creates new form mainWindow
     */
    public mainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        startButton = new javax.swing.JButton();
        ApplicationTitle = new javax.swing.JLabel();
        projectName = new javax.swing.JTextField();
        projectNameLable = new javax.swing.JLabel();
        BrowseButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Smart ETL Tool");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(254, 254, 254));
        setBounds(new java.awt.Rectangle(200, 200, 400, 200));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(400, 200));
        setMinimumSize(new java.awt.Dimension(400, 200));
        setSize(new java.awt.Dimension(400, 200));
        getContentPane().setLayout(null);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 50, 400, 10);

        startButton.setText("Start");
        startButton.setMaximumSize(new java.awt.Dimension(400, 200));
        startButton.setMinimumSize(new java.awt.Dimension(400, 200));
        startButton.setPreferredSize(new java.awt.Dimension(400, 200));
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });
        getContentPane().add(startButton);
        startButton.setBounds(270, 110, 120, 30);

        ApplicationTitle.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        ApplicationTitle.setText("Smart ETL Tool");
        getContentPane().add(ApplicationTitle);
        ApplicationTitle.setBounds(120, 0, 170, 50);
        getContentPane().add(projectName);
        projectName.setBounds(70, 60, 230, 25);

        projectNameLable.setText("Project");
        getContentPane().add(projectNameLable);
        projectNameLable.setBounds(10, 60, 44, 20);

        BrowseButton.setText("Browse");
        BrowseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrowseButtonActionPerformed(evt);
            }
        });
        getContentPane().add(BrowseButton);
        BrowseButton.setBounds(310, 60, 80, 27);

        jLabel1.setText("Choos Project file Or Enter project name To Create Project");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 90, 390, 15);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
    	String project = this.projectName.getText();
    	if( projFile == null && !project.equals(""))
         	Configuration.init(project);
    	 else if( projFile != null )
    	 {
    		 if(!Configuration.init(projFile)){
    			 JOptionPane.showMessageDialog(this, "Invalid File");
        		 return;
    		 }
    	 }
    	 else{
    		 JOptionPane.showMessageDialog(this, "Please Enter Project Name");
    		 return;
    	 }
    	DesktopPane frame = new DesktopPane();
        frame.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        frame.setBounds(800, 500, 800, 500);
        frame.setVisible(true);
        frame.setTitle("Smart ETL Tool");
        this.setVisible(false);
       
       
    }//GEN-LAST:event_startButtonActionPerformed

    private void BrowseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrowseButtonActionPerformed
    	jFileChooser1 = new JFileChooser();
    	FileNameExtensionFilter filter = new FileNameExtensionFilter("ETL Tool Project File", "Properties", "properties");
    	jFileChooser1.setFileFilter(filter);
    	int returnVal = jFileChooser1.showOpenDialog(this);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            projFile = jFileChooser1.getSelectedFile();
            jFileChooser1.setDialogTitle("Choose Project File");
            this.projectName.setText(projFile.getAbsolutePath());
        } else {
        }
    }//GEN-LAST:event_BrowseButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ApplicationTitle;
    private javax.swing.JButton BrowseButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField projectName;
    private javax.swing.JLabel projectNameLable;
    private javax.swing.JButton startButton;
    private File projFile;
    private JFileChooser jFileChooser1 ;
    // End of variables declaration//GEN-END:variables
}
