/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package smartEtl.frames;

import javax.swing.JOptionPane;

import smartEtl.config.Configuration;
import smartEtl.config.PropertiesName;
import smartEtl.core.utils;

/**
 *
 * @author furqan
 */
public class srcConnection extends javax.swing.JInternalFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
     * Creates new form srcConnection
     */
    public srcConnection() {
         super("Source Connection", true,true, true, true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        srcDB = new javax.swing.JComboBox<>();
        srcDBlable = new javax.swing.JLabel();
        srcDBUrl = new javax.swing.JTextField();
        srcDBUrlLable = new javax.swing.JLabel();
        srcDBPort = new javax.swing.JTextField();
        srcDBPortLable = new javax.swing.JLabel();
        srcDBUserName = new javax.swing.JTextField();
        srcDBUserNameLable = new javax.swing.JLabel();
        srcDBPassword = new javax.swing.JTextField();
        srcDBPasswordLable = new javax.swing.JLabel();
        srcDBSaveButton = new javax.swing.JButton();
        srcDBTestButton = new javax.swing.JButton();
        srcDataBase = new javax.swing.JTextField();
        srcDBLable = new javax.swing.JLabel();

        srcDB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MySQl Server", "SQL Server", "Postgre Server", "Oracle" }));

        srcDBlable.setText("Select DB");

        srcDBUrl.setBackground(new java.awt.Color(254, 254, 254));

        srcDBUrlLable.setText("DB URL");

        srcDBPort.setBackground(new java.awt.Color(254, 254, 254));

        srcDBPortLable.setText("Port");

        srcDBUserName.setBackground(new java.awt.Color(254, 254, 254));

        srcDBUserNameLable.setText("User Name");

        srcDBPassword.setBackground(new java.awt.Color(254, 254, 254));

        srcDBPasswordLable.setText("Password");

        srcDBSaveButton.setText("Save");
        srcDBSaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srcDBSaveButtonActionPerformed(evt);
            }
        });

        srcDBTestButton.setText("Test");
        srcDBTestButton.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                srcDBTestButtonInputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        srcDBTestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srcDBTestButtonActionPerformed(evt);
            }
        });

        srcDataBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srcDataBaseActionPerformed(evt);
            }
        });

        srcDBLable.setText("DataBase");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(srcDBSaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addComponent(srcDBTestButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(srcDBPassword)
                    .addComponent(srcDBUserName)
                    .addComponent(srcDBUrl)
                    .addComponent(srcDB, 0, 189, Short.MAX_VALUE)
                    .addComponent(srcDBPort, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(srcDataBase))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(srcDBUserNameLable)
                    .addComponent(srcDBPasswordLable, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(srcDBPortLable, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(srcDBUrlLable, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(srcDBlable, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(srcDBLable))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(srcDB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(srcDBlable))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(srcDBUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(srcDBUrlLable))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(srcDBPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(srcDBPortLable))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(srcDataBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(srcDBLable))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(srcDBUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(srcDBUserNameLable))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(srcDBPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(srcDBPasswordLable))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(srcDBSaveButton)
                    .addComponent(srcDBTestButton))
                .addGap(36, 36, 36))
        );

        loadFields();
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadFields(){
    	srcDB.setSelectedIndex(utils.getDriverClassIndex(Configuration.getAttribute(PropertiesName.srcDriver)));
    	srcDBUrl.setText(Configuration.getAttribute(PropertiesName.srcUrl));
    	srcDBPort.setText(Configuration.getAttribute(PropertiesName.srcPort));
    	srcDataBase.setText(Configuration.getAttribute(PropertiesName.srcDB));
    	srcDBUserName.setText(Configuration.getAttribute(PropertiesName.srcUser));
    	srcDBPassword.setText(Configuration.getAttribute(PropertiesName.srcPassword));
    }
    private void srcDBTestButtonInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_srcDBTestButtonInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_srcDBTestButtonInputMethodTextChanged

    private void srcDBTestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srcDBTestButtonActionPerformed
    	int index = srcDB.getSelectedIndex();
    	String url  = srcDBUrl.getText();
    	String port = srcDBPort.getText();
    	String database = srcDataBase.getText();
    	String user = srcDBUserName.getText();
    	String pass = srcDBPassword.getText();
    	boolean status = this.testDB(index, url, port,database, user, pass); 
    	if( status )
        JOptionPane.showMessageDialog(this, "DB Ping Sucessfully");
        else
        JOptionPane.showMessageDialog(this, "Error in Connection");
    }//GEN-LAST:event_srcDBTestButtonActionPerformed

    private boolean testDB(int index,String url,String port,String database, String user,String pass){
    	boolean status = utils.testConnection(index,url,port,database,user,pass);
    	return status;
    }
    
    private void srcDBSaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srcDBSaveButtonActionPerformed
    	int index = srcDB.getSelectedIndex();
    	String driverClass = utils.getDriverClass(index);
    	String url  = srcDBUrl.getText();
    	String port = srcDBPort.getText();
    	String database = srcDataBase.getText();
    	String user = srcDBUserName.getText();
    	String pass = srcDBPassword.getText();
    	boolean status = this.testDB(index, url, port,database, user, pass); 
    	if( status ){
    		Configuration.addAttribute(PropertiesName.srcDriver, driverClass);
        	Configuration.addAttribute(PropertiesName.srcUrl, url);
        	Configuration.addAttribute(PropertiesName.srcPort, port);
        	Configuration.addAttribute(PropertiesName.srcUser, user);
        	Configuration.addAttribute(PropertiesName.srcDB, database);
        	Configuration.addAttribute(PropertiesName.srcPassword, pass);
        	Configuration.saveConfig();
            JOptionPane.showMessageDialog(this, "Data Saved");
        }
        else
            JOptionPane.showMessageDialog(this, "Error in Connection- fix Params");
    }//GEN-LAST:event_srcDBSaveButtonActionPerformed

    private void srcDataBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srcDataBaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_srcDataBaseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> srcDB;
    private javax.swing.JLabel srcDBLable;
    private javax.swing.JTextField srcDBPassword;
    private javax.swing.JLabel srcDBPasswordLable;
    private javax.swing.JTextField srcDBPort;
    private javax.swing.JLabel srcDBPortLable;
    private javax.swing.JButton srcDBSaveButton;
    private javax.swing.JButton srcDBTestButton;
    private javax.swing.JTextField srcDBUrl;
    private javax.swing.JLabel srcDBUrlLable;
    private javax.swing.JTextField srcDBUserName;
    private javax.swing.JLabel srcDBUserNameLable;
    private javax.swing.JLabel srcDBlable;
    private javax.swing.JTextField srcDataBase;
    // End of variables declaration//GEN-END:variables
}
