/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package smartEtl.frames;

import java.sql.Connection;
import java.util.ArrayList;

import smartEtl.core.utils;

/**
 *
 * @author furqan
 */
public class Transformations extends javax.swing.JInternalFrame {

    /**
     * Creates new form Transformations
     */
    public Transformations() {
    	super("Tables", true,true, true, true);
    ArrayList<String> tables = new ArrayList<String>();
    	Connection conn = utils.getConnection("src");
    	if(conn != null){
        	tables = utils.getTables(conn);
    	}
    	String[] tablesList = new String[tables.size()];
    	for( int i = 0 ; i < tables.size() ; i++){
    		tablesList[i] = tables.get(i);
    	}
    	
        initComponents(tablesList);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents(String[] tablesList) {

        TablesList = new javax.swing.JComboBox<>();
        SelectTableButton = new javax.swing.JButton();

        TablesList.setModel(new javax.swing.DefaultComboBoxModel<>(tablesList));

        SelectTableButton.setText("Show");
        SelectTableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectTableButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TablesList, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SelectTableButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TablesList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SelectTableButton))
                .addContainerGap(238, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SelectTableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectTableButtonActionPerformed
    	Object table= TablesList.getSelectedItem();
    	table.toString();
    }//GEN-LAST:event_SelectTableButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SelectTableButton;
    private javax.swing.JComboBox<String> TablesList;
    // End of variables declaration//GEN-END:variables
}
