/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import javax.swing.JOptionPane;

import core.utils;

/**
 *
 * @author furqan
 */
public class destConnection extends javax.swing.JInternalFrame {

    /**
     * Creates new form destConnection
     */
    public destConnection() {
        super("Destination Connection", true,true, true, true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        destDB = new javax.swing.JComboBox<>();
        destDBlable = new javax.swing.JLabel();
        destDBUrl = new javax.swing.JTextField();
        destDBUrlLable = new javax.swing.JLabel();
        destDBPort = new javax.swing.JTextField();
        destDBPortLable = new javax.swing.JLabel();
        destDBUserName = new javax.swing.JTextField();
        destDBUserNameLable = new javax.swing.JLabel();
        destDBPassword = new javax.swing.JTextField();
        destDBPasswordLable = new javax.swing.JLabel();
        destDBSaveButton = new javax.swing.JButton();
        destDBTestButton = new javax.swing.JButton();

        destDB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MySQl Server", "SQL Server", "Postgre Server", "Oracle" }));

        destDBlable.setText("Select DB");

        destDBUrl.setBackground(new java.awt.Color(254, 254, 254));

        destDBUrlLable.setText("DB URL");

        destDBPort.setBackground(new java.awt.Color(254, 254, 254));

        destDBPortLable.setText("Port");

        destDBUserName.setBackground(new java.awt.Color(254, 254, 254));

        destDBUserNameLable.setText("User Name");

        destDBPassword.setBackground(new java.awt.Color(254, 254, 254));

        destDBPasswordLable.setText("Password");

        destDBSaveButton.setText("Save");
        destDBSaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destDBSaveButtonActionPerformed(evt);
            }
        });

        destDBTestButton.setText("Test");
        destDBTestButton.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                destDBTestButtonInputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        destDBTestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destDBTestButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(destDBSaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addComponent(destDBTestButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(destDBPassword)
                    .addComponent(destDBUserName)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(destDBUrl)
                            .addComponent(destDB, 0, 189, Short.MAX_VALUE))
                        .addComponent(destDBPort, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(destDBUserNameLable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(destDBPortLable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(destDBUrlLable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(destDBlable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(destDBPasswordLable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(destDB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(destDBlable))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(destDBUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(destDBUrlLable))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(destDBPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(destDBPortLable))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(destDBUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(destDBUserNameLable))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(destDBPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(destDBPasswordLable))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(destDBSaveButton)
                    .addComponent(destDBTestButton))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void destDBTestButtonInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_destDBTestButtonInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_destDBTestButtonInputMethodTextChanged

    private void destDBTestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destDBTestButtonActionPerformed
        boolean status = utils.testConnection(0, destDBUrl.getText(), destDBPort.getText(), destDBUserName.getText(), destDBPassword.getText());
        if( status )
        JOptionPane.showMessageDialog(this, "DB Ping Sucessfully");
        else
        JOptionPane.showMessageDialog(this, "Error in Connection");
    }//GEN-LAST:event_destDBTestButtonActionPerformed

    private void destDBSaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destDBSaveButtonActionPerformed
        boolean status = utils.testConnection(0, destDBUrl.getText(), destDBPort.getText(), destDBUserName.getText(), destDBPassword.getText());
        if( status ){
            JOptionPane.showMessageDialog(this, "Data Saved");
        }
        else
            JOptionPane.showMessageDialog(this, "Error in Connection- fix Params");
    }//GEN-LAST:event_destDBSaveButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> destDB;
    private javax.swing.JTextField destDBPassword;
    private javax.swing.JLabel destDBPasswordLable;
    private javax.swing.JTextField destDBPort;
    private javax.swing.JLabel destDBPortLable;
    private javax.swing.JButton destDBSaveButton;
    private javax.swing.JButton destDBTestButton;
    private javax.swing.JTextField destDBUrl;
    private javax.swing.JLabel destDBUrlLable;
    private javax.swing.JTextField destDBUserName;
    private javax.swing.JLabel destDBUserNameLable;
    private javax.swing.JLabel destDBlable;
    // End of variables declaration//GEN-END:variables
}
