/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package smartEtl.Screens;

import java.awt.Color;
import java.sql.Connection;

import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;

import smartEtl.operations.ConfigurationService;
import smartEtl.operations.DataBaseModule;

/**
 *
 * @author furqan
 */
public class DesktopPane extends javax.swing.JFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private JDesktopPane desktopPane;

    /**
     * Creates new form DesktopPane
     */
    public DesktopPane() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

    	desktopPane = new JDesktopPane();
    	desktopPane.setBackground(Color.green);
    	this.setContentPane(desktopPane);
    	
        mainMenue = new javax.swing.JMenuBar();
        fileMenue = new javax.swing.JMenu();
        srcConnectionMenue = new javax.swing.JMenuItem();
        destConnectionMenue = new javax.swing.JMenuItem();
        ViewSourceDataMenue = new javax.swing.JMenuItem();
        ETLProcessesMenue = new javax.swing.JMenuItem();
        ViewDestinationDataMenue = new javax.swing.JMenuItem();
        exitMenue = new javax.swing.JMenuItem();
        aboutMenue = new javax.swing.JMenu();
        aboutetl = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileMenue.setText("File");

        srcConnectionMenue.setText("Source Connection");
        srcConnectionMenue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srcConnectionMenueActionPerformed(evt);
            }
        });
        fileMenue.add(srcConnectionMenue);

        destConnectionMenue.setText("Destination Connection");
        destConnectionMenue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destConnectionMenueActionPerformed(evt);
            }
        });
        fileMenue.add(destConnectionMenue);

        ViewSourceDataMenue.setText("View Source Data");
        ViewSourceDataMenue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewSourceDataMenueActionPerformed(evt);
            }
        });
        fileMenue.add(ViewSourceDataMenue);

        ETLProcessesMenue.setText("ETL Processes");
        ETLProcessesMenue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ETLProcessesMenueActionPerformed(evt);
            }
        });
        fileMenue.add(ETLProcessesMenue);

        ViewDestinationDataMenue.setText("View Destination Data");
        ViewDestinationDataMenue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewDestinationDataMenueActionPerformed(evt);
            }
        });
        fileMenue.add(ViewDestinationDataMenue);

        exitMenue.setText("Exit");
        exitMenue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenueActionPerformed(evt);
            }
        });
        fileMenue.add(exitMenue);

        mainMenue.add(fileMenue);

        aboutMenue.setText("About");

        aboutetl.setText("About-ETL");
        aboutetl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutetlActionPerformed(evt);
            }
        });
        aboutMenue.add(aboutetl);

        mainMenue.add(aboutMenue);

        setJMenuBar(mainMenue);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 285, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenueActionPerformed
    	ConfigurationService.saveConfig();
    	System.exit(0);
    }//GEN-LAST:event_exitMenueActionPerformed

    private void destConnectionMenueActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        ConnectionTest dest = new ConnectionTest("dest");
        dest.setLocation(100, 100);
        dest.setVisible(true);
        desktopPane.add(dest);
    } 
    
    private void srcConnectionMenueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destConnectionMenueActionPerformed
    	ConnectionTest srcCon = new ConnectionTest("src");
        srcCon.setLocation(100, 100);
        srcCon.setVisible(true);
        desktopPane.add(srcCon);
    }//GEN-LAST:event_destConnectionMenueActionPerformed

    private void aboutetlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutetlActionPerformed
        About about = new About();
        about.setLocation(100, 100);
        about.setVisible(true);
        desktopPane.add(about);
    }//GEN-LAST:event_aboutetlActionPerformed

    private void ViewSourceDataMenueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewSourceDataMenueActionPerformed

    	loadTablesFor("src");
    	
    }//GEN-LAST:event_ViewSourceDataMenueActionPerformed

    private void ViewDestinationDataMenueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewDestinationDataMenueActionPerformed
    	
    	loadTablesFor("dest");
    	
    }//GEN-LAST:event_ViewDestinationDataMenueActionPerformed

    public void loadTablesFor(String dataFor){
    	Connection conn = DataBaseModule.getConnection(dataFor);
    	if( conn != null){
    		
	    	TablesList tables = new TablesList(conn , dataFor);
	    	tables.setLocation(100, 100);
	    	tables.setVisible(true);
	        desktopPane.add(tables);
    	}
    	else{
    		JOptionPane.showMessageDialog(null, "Please Enter Configurations First");
    	}
    }
    private void ETLProcessesMenueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ETLProcessesMenueActionPerformed
		Transformations tables = new Transformations();
    	tables.setLocation(100, 100);
    	tables.setVisible(true);
        desktopPane.add(tables);
			
    }//GEN-LAST:event_ETLProcessesMenueActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ETLProcessesMenue;
    private javax.swing.JMenuItem ViewDestinationDataMenue;
    private javax.swing.JMenuItem ViewSourceDataMenue;
    private javax.swing.JMenu aboutMenue;
    private javax.swing.JMenuItem aboutetl;
    private javax.swing.JMenuItem destConnectionMenue;
    private javax.swing.JMenuItem exitMenue;
    private javax.swing.JMenu fileMenue;
    private javax.swing.JMenuBar mainMenue;
    private javax.swing.JMenuItem srcConnectionMenue;
    // End of variables declaration//GEN-END:variables
}
